name: Xcode Build and Upload

on:
  workflow_dispatch:

jobs:
  build:
    name: Build default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_14.3.1.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Build
      run: xcodebuild -configuration Deployment -sdk macosx13.3
    - name: Tar files
      run: (cd build/Deployment/; tar -cvf ../../cooViewer.app.tar cooViewer.app)
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cooViewer.app.tar
        path: cooViewer.app.tar
